name: Sync to GitLab
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Enviar para GitLab
        run: |
          git remote add gitlab https://oauth2:glpat-sPsEJAPG2XUi_RzRKzR5@gitlab.com/PabloMangion/breizhsport-backend.git
          git push --mirror gitlab
